all:
	gcc AcceptConnection.c CreateServerSocket.c CreateThread.c Logger.c HandleClient.c PacketManager.c ConfigFromFile.c Main.c -lpthread -o "Free Simple Server"
clean:
	rm -rf *o *.c~ *.h~ *.log~ "Free Simple Server"
